// Re-export barrel — canonical source is now src/styles/obsidianTheme.css.ts
export {
  vars,
  studyThemeClass,
  themeRoot,
  ambientOrb,
  panelBase,
  panelInset,
  sectionHeader,
  sectionHeaderStack,
  sectionEyebrow,
  sectionTitle,
  panelTitle,
  sectionDescription,
  panelDescription,
  monoMeta,
  iconFrame,
  divider,
  textLink,
  actionButton,
  filterPill,
  badge,
  emptyState,
  loadingState,
  loadingSpinner,
} from '../../styles/obsidianTheme.css.ts';
