-- ============================================
-- COMBINED TIMELINE EVENTS MIGRATION
-- Copy and paste this entire file into Supabase SQL Editor
-- ============================================

-- Create the table
CREATE TABLE IF NOT EXISTS timeline_events (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    year INTEGER NOT NULL,
    month INTEGER,
    day INTEGER,
    end_year INTEGER,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    detailed_description TEXT,
    category TEXT NOT NULL CHECK (category IN ('biography', 'academic', 'publication', 'organization', 'historical', 'revolution', 'war', 'economic')),
    importance TEXT DEFAULT 'normal' CHECK (importance IN ('minor', 'normal', 'major', 'critical')),
    location TEXT,
    image_url TEXT,
    wikipedia_url TEXT,
    marxists_org_url TEXT,
    related_people TEXT[],
    tags TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_timeline_events_year ON timeline_events(year);
CREATE INDEX IF NOT EXISTS idx_timeline_events_category ON timeline_events(category);

-- RLS Policies
ALTER TABLE timeline_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Timeline events are publicly readable" ON timeline_events;
CREATE POLICY "Timeline events are publicly readable"
    ON timeline_events FOR SELECT
    USING (true);

-- ============================================
-- I. PRE-HISTORY (1649-1831)
-- ============================================

INSERT INTO timeline_events (year, month, day, title, description, detailed_description, category, importance, location, related_people, tags, wikipedia_url, image_url) VALUES

(1649, 1, 30, 'Execution of Charles I', 'The English Revolution beheads the divine right of kings', 
'The English Revolution (Cromwell) beheads the divine right of kings, establishing the supremacy of Parliament. The Diggers led by Gerrard Winstanley occupy St. George''s Hill, demanding common ownership of land ("The Earth is a Common Treasury"), prefiguring communism.',
'revolution', 'critical', 'Whitehall, London',
ARRAY['Oliver Cromwell', 'Charles I', 'Gerrard Winstanley'],
ARRAY['english-revolution', 'bourgeois-revolution', 'diggers'],
'https://en.wikipedia.org/wiki/Execution_of_Charles_I',
'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/The_Execution_of_Charles_I_of_England.jpg/1280px-The_Execution_of_Charles_I_of_England.jpg'),

(1789, 7, 14, 'Storming of the Bastille', 'The French Revolution begins', 
'The urban poor (sans-culottes) provide the shock troops for the bourgeois National Assembly. The fall of the Bastille marks the symbolic beginning of the French Revolution.',
'revolution', 'critical', 'Paris, France',
ARRAY['Louis XVI'],
ARRAY['french-revolution', 'bastille', 'sans-culottes'],
'https://en.wikipedia.org/wiki/Storming_of_the_Bastille',
'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Prise_de_la_Bastille.jpg/1280px-Prise_de_la_Bastille.jpg'),

(1791, 8, NULL, 'Haitian Revolution Begins', 'The only successful slave revolt in history', 
'Toussaint Louverture leads the only successful slave revolt in history, forcing the Enlightenment to confront its racial hypocrisy. Establishes that "Rights of Man" must include the Black slave.',
'revolution', 'critical', 'Saint-Domingue (Haiti)',
ARRAY['Toussaint Louverture'],
ARRAY['haiti', 'slave-revolt', 'anti-colonialism'],
'https://en.wikipedia.org/wiki/Haitian_Revolution',
'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Toussaint_L%27Ouverture.jpg/800px-Toussaint_L%27Ouverture.jpg'),

(1793, 1, 21, 'Execution of Louis XVI', 'The Jacobin Terror begins under Robespierre', 
'The "Committee of Public Safety" centralizes power to defend the revolution against feudal Europe. The execution marks the radicalization of the revolution.',
'revolution', 'major', 'Paris, France',
ARRAY['Louis XVI', 'Maximilien Robespierre'],
ARRAY['french-revolution', 'jacobin', 'terror'],
'https://en.wikipedia.org/wiki/Execution_of_Louis_XVI',
'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Execution_of_Louis_XVI.jpg/1024px-Execution_of_Louis_XVI.jpg'),

(1796, NULL, NULL, 'Conspiracy of Equals', 'First explicitly communist conspiracy', 
'Gracchus Babeuf and Sylvain Maréchal organize the first communist conspiracy, demanding abolition of private property. Babeuf executed in 1797.',
'revolution', 'major', 'Paris, France',
ARRAY['Gracchus Babeuf', 'Sylvain Maréchal'],
ARRAY['babeuf', 'conspiracy-of-equals', 'proto-communism'],
'https://en.wikipedia.org/wiki/Conspiracy_of_the_Equals',
'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Fran%C3%A7ois-No%C3%ABl_Babeuf.jpg/800px-Fran%C3%A7ois-No%C3%ABl_Babeuf.jpg'),

(1804, 1, 1, 'Independence of Haiti', 'The first Black Republic is declared', 
'Jean-Jacques Dessalines rips the white stripe from the French tricolor. Haiti becomes the first independent Black republic.',
'revolution', 'critical', 'Haiti',
ARRAY['Jean-Jacques Dessalines', 'Toussaint Louverture'],
ARRAY['haiti', 'independence', 'abolition'],
'https://en.wikipedia.org/wiki/Haitian_Declaration_of_Independence',
'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Jean-Jacques-Dessalines.jpg/800px-Jean-Jacques-Dessalines.jpg'),

(1815, 6, 18, 'Defeat of Napoleon at Waterloo', 'The Bourbon Restoration begins', 
'The Congress of Vienna tries to freeze history, but the Napoleonic Code remains, embedding bourgeois property relations across Europe.',
'historical', 'major', 'Waterloo, Belgium',
ARRAY['Napoleon Bonaparte'],
ARRAY['napoleon', 'waterloo', 'restoration'],
'https://en.wikipedia.org/wiki/Battle_of_Waterloo',
'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Sadler%2C_Battle_of_Waterloo.jpg/1280px-Sadler%2C_Battle_of_Waterloo.jpg'),

(1818, 5, 5, 'Birth of Karl Marx', 'Karl Marx is born in Trier, Prussia', 
'Karl Heinrich Marx was born into a middle-class family in Trier, in the Prussian Rhineland.',
'biography', 'critical', 'Trier, Prussia',
ARRAY['Karl Marx'],
ARRAY['marx', 'birth'],
'https://en.wikipedia.org/wiki/Karl_Marx',
'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Karl_Marx_001.jpg/800px-Karl_Marx_001.jpg'),

(1820, 11, 28, 'Birth of Friedrich Engels', 'Friedrich Engels is born in Barmen, Prussia', 
'Engels was born into a wealthy textile manufacturing family. He would become Marx''s closest collaborator.',
'biography', 'critical', 'Barmen, Prussia',
ARRAY['Friedrich Engels'],
ARRAY['engels', 'birth'],
'https://en.wikipedia.org/wiki/Friedrich_Engels',
'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Friedrich_Engels_portrait_%28cropped%29.jpg/800px-Friedrich_Engels_portrait_%28cropped%29.jpg'),

(1831, 11, NULL, 'Silk Weavers'' Revolt (Canuts)', 'First independent working class uprising', 
'Lyon silk weavers seize the city: "Live working or die fighting." The black flag is flown for the first time as a symbol of proletarian hunger.',
'revolution', 'major', 'Lyon, France',
ARRAY[]::TEXT[],
ARRAY['canuts', 'lyon', 'workers-uprising', 'black-flag'],
'https://en.wikipedia.org/wiki/Canut_revolts',
'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Deveria_-_Combat_de_la_Croix-Rousse.jpg/1024px-Deveria_-_Combat_de_la_Croix-Rousse.jpg'),

-- ============================================
-- II. BIRTH OF THEORY (1844-1871)
-- ============================================

(1844, 8, NULL, 'Marx and Engels Meet in Paris', 'The partnership begins', 
'Marx and Engels meet at the Café de la Régence. They discover they arrived at the same conclusions independently. The most important intellectual partnership begins.',
'biography', 'critical', 'Paris, France',
ARRAY['Karl Marx', 'Friedrich Engels'],
ARRAY['marx', 'engels', 'partnership'],
'https://en.wikipedia.org/wiki/Karl_Marx',
NULL),

(1845, NULL, NULL, 'Marx Writes The German Ideology', 'Materialist conception of history formulated', 
'"The ruling ideas of each age have ever been the ideas of its ruling class." Unpublished in his lifetime.',
'publication', 'major', 'Brussels, Belgium',
ARRAY['Karl Marx', 'Friedrich Engels'],
ARRAY['german-ideology', 'historical-materialism'],
'https://en.wikipedia.org/wiki/The_German_Ideology',
NULL),

(1847, 6, NULL, 'Communist League Founded', 'Working Men of All Countries, Unite!', 
'The League of the Just becomes the Communist League, adopting "Working Men of All Countries, Unite!"',
'organization', 'major', 'London, England',
ARRAY['Karl Marx', 'Friedrich Engels'],
ARRAY['communist-league', 'international'],
'https://en.wikipedia.org/wiki/Communist_League',
NULL),

(1848, 2, 21, 'Communist Manifesto Published', 'The most influential political pamphlet in history', 
'"A spectre is haunting Europe—the spectre of communism." Published days before revolution erupts in Paris.',
'publication', 'critical', 'London, England',
ARRAY['Karl Marx', 'Friedrich Engels'],
ARRAY['manifesto', 'communism', '1848'],
'https://en.wikipedia.org/wiki/The_Communist_Manifesto',
'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Communist-manifesto.png/800px-Communist-manifesto.png'),

(1848, 3, NULL, 'The Springtime of Nations', 'Revolutions erupt across Europe', 
'Revolutions across Europe. Marx and Engels edit the Neue Rheinische Zeitung in Cologne as the extreme left wing of democracy.',
'revolution', 'critical', 'Europe',
ARRAY['Karl Marx', 'Friedrich Engels'],
ARRAY['1848', 'revolution', 'springtime-of-nations'],
'https://en.wikipedia.org/wiki/Revolutions_of_1848',
'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Maerz1848_berlin.jpg/1024px-Maerz1848_berlin.jpg'),

(1848, 6, NULL, 'June Days Uprising', 'Definitive split between bourgeoisie and proletariat', 
'Paris workers rise against the bourgeois republic. 3,000 slaughtered. The bourgeoisie and proletariat part ways definitively.',
'revolution', 'critical', 'Paris, France',
ARRAY[]::TEXT[],
ARRAY['june-days', '1848', 'class-struggle'],
'https://en.wikipedia.org/wiki/June_Days_uprising',
'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Horace_Vernet-Barricade_rue_Soufflot.jpg/1024px-Horace_Vernet-Barricade_rue_Soufflot.jpg'),

(1852, NULL, NULL, 'The Eighteenth Brumaire', 'Analysis of 1848''s failure', 
'Marx analyzes 1848 and introduces "dictatorship of the proletariat." "History repeats itself, first as tragedy, then as farce."',
'publication', 'major', 'London, England',
ARRAY['Karl Marx'],
ARRAY['eighteenth-brumaire', 'class-analysis'],
'https://en.wikipedia.org/wiki/The_Eighteenth_Brumaire_of_Louis_Bonaparte',
NULL),

(1864, 9, 28, 'First International Founded', 'IWA established at St. Martin''s Hall', 
'Marx delivers the Inaugural Address: "The emancipation of the working classes must be conquered by the working classes themselves."',
'organization', 'critical', 'London, England',
ARRAY['Karl Marx'],
ARRAY['first-international', 'iwma'],
'https://en.wikipedia.org/wiki/International_Workingmen%27s_Association',
NULL),

(1867, 9, 14, 'Capital Volume I Published', 'The most terrible missile hurled at the bourgeoisie', 
'Published in Hamburg. Marx: "the most terrible missile that has yet been hurled at the heads of the bourgeoisie."',
'publication', 'critical', 'Hamburg, Germany',
ARRAY['Karl Marx'],
ARRAY['capital', 'das-kapital', 'surplus-value'],
'https://en.wikipedia.org/wiki/Das_Kapital',
'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Zentralbibliothek_Z%C3%BCrich_Das_Kapital_Marx_1867.jpg/800px-Zentralbibliothek_Z%C3%BCrich_Das_Kapital_Marx_1867.jpg'),

(1869, NULL, NULL, 'SDAP Founded in Eisenach', 'First mass Marxist party', 
'August Bebel and Wilhelm Liebknecht found the Social Democratic Workers'' Party - the first mass Marxist party.',
'organization', 'major', 'Eisenach, Germany',
ARRAY['August Bebel', 'Wilhelm Liebknecht'],
ARRAY['sdap', 'german-socialism'],
'https://en.wikipedia.org/wiki/Social_Democratic_Workers%27_Party_of_Germany',
NULL),

(1870, 4, 22, 'Birth of Vladimir Lenin', 'Lenin is born in Simbirsk', 
'Vladimir Ilyich Ulyanov born into a middle-class family. His brother Alexander executed in 1887 for plotting against the Tsar.',
'biography', 'critical', 'Simbirsk, Russia',
ARRAY['Vladimir Lenin'],
ARRAY['lenin', 'birth'],
'https://en.wikipedia.org/wiki/Vladimir_Lenin',
'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Lenin_circa_1887.jpg/800px-Lenin_circa_1887.jpg'),

(1871, 3, 18, 'The Paris Commune Begins', 'First workers'' government in history', 
'Workers seize power in Paris. They abolish the standing army and separate church from state. Marx: "The working class cannot simply lay hold of the ready-made state machinery."',
'revolution', 'critical', 'Paris, France',
ARRAY['Karl Marx'],
ARRAY['paris-commune', 'workers-government'],
'https://en.wikipedia.org/wiki/Paris_Commune',
'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Barricade18March1871.jpg/1024px-Barricade18March1871.jpg'),

(1871, 5, 28, 'Fall of the Paris Commune', 'Bloody Week - 20,000 executed', 
'The Commune crushed during Semaine Sanglante. 20,000 workers executed by Versailles forces.',
'revolution', 'critical', 'Paris, France',
ARRAY[]::TEXT[],
ARRAY['paris-commune', 'bloody-week', 'martyrs'],
'https://en.wikipedia.org/wiki/Bloody_Week',
'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Communards_in_their_coffins.jpg/1024px-Communards_in_their_coffins.jpg'),

-- ============================================
-- III. AGE OF IMPERIALISM (1875-1914)
-- ============================================

(1875, NULL, NULL, 'Gotha Congress', 'Marx attacks reformist slogans', 
'Marxists merge with Lassalleans to form SAPD (later SPD). Marx writes Critique of the Gotha Programme.',
'organization', 'major', 'Gotha, Germany',
ARRAY['Karl Marx', 'Ferdinand Lassalle'],
ARRAY['gotha', 'spd', 'critique'],
'https://en.wikipedia.org/wiki/Critique_of_the_Gotha_Programme',
NULL),

(1882, NULL, NULL, 'First Russian Translation of Manifesto', 'Plekhanov translates the Manifesto', 
'Marx speculates if Russian Obshchina can skip capitalism - yes, if supported by Western revolution.',
'publication', 'normal', 'Geneva, Switzerland',
ARRAY['Georgi Plekhanov', 'Karl Marx'],
ARRAY['manifesto', 'translation', 'russia'],
'https://en.wikipedia.org/wiki/Georgi_Plekhanov',
NULL),

(1883, 3, 14, 'Death of Karl Marx', 'The founder of scientific socialism dies', 
'Marx dies in London at age 64. Buried at Highgate Cemetery. Engels: "His name will endure through the ages."',
'biography', 'critical', 'London, England',
ARRAY['Karl Marx', 'Friedrich Engels'],
ARRAY['marx', 'death', 'highgate'],
'https://en.wikipedia.org/wiki/Karl_Marx',
'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Marx%27s_grave_in_Highgate_Cemetery.jpg/800px-Marx%27s_grave_in_Highgate_Cemetery.jpg'),

(1886, 5, 4, 'Haymarket Affair', 'Origin of May Day', 
'Anarchist bombing and police riot lead to execution of labor leaders. Becomes origin of International Workers'' Day.',
'historical', 'major', 'Chicago, USA',
ARRAY['Albert Parsons', 'August Spies'],
ARRAY['haymarket', 'may-day', 'labor'],
'https://en.wikipedia.org/wiki/Haymarket_affair',
'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Haymarket_Riot-Harpers_Weekly.jpg/1024px-Haymarket_Riot-Harpers_Weekly.jpg'),

(1889, 7, 14, 'Second International Founded', 'Socialist parties unite globally', 
'Founded on the centenary of the French Revolution. Adopts May 1st as global demonstration day.',
'organization', 'major', 'Paris, France',
ARRAY['Friedrich Engels'],
ARRAY['second-international', 'may-day'],
'https://en.wikipedia.org/wiki/Second_International',
NULL),

(1895, 8, 5, 'Death of Friedrich Engels', 'Engels dies in London', 
'Engels dies of throat cancer at age 74. Left estate to Marx daughters.',
'biography', 'major', 'London, England',
ARRAY['Friedrich Engels'],
ARRAY['engels', 'death'],
'https://en.wikipedia.org/wiki/Friedrich_Engels',
NULL),

(1898, NULL, NULL, 'RSDLP Founded', 'Russian Social Democratic Labour Party', 
'Founded in Minsk in a small wooden house. Most delegates arrested shortly after.',
'organization', 'major', 'Minsk, Russian Empire',
ARRAY['Vladimir Lenin'],
ARRAY['rsdlp', 'russia'],
'https://en.wikipedia.org/wiki/Russian_Social_Democratic_Labour_Party',
NULL),

(1902, NULL, NULL, 'What Is To Be Done?', 'Theory of the vanguard party', 
'Lenin argues against Economism. Revolutionary consciousness must be brought to the class by a vanguard party.',
'publication', 'critical', 'Stuttgart, Germany',
ARRAY['Vladimir Lenin'],
ARRAY['lenin', 'vanguard', 'party'],
'https://en.wikipedia.org/wiki/What_Is_to_Be_Done%3F',
NULL),

(1903, 7, NULL, 'Bolshevik-Menshevik Split', 'Split over party organization', 
'At the Second Congress, party splits between Bolsheviks (Lenin) and Mensheviks (Martov).',
'organization', 'critical', 'London/Brussels',
ARRAY['Vladimir Lenin', 'Julius Martov'],
ARRAY['bolshevik', 'menshevik', 'split'],
'https://en.wikipedia.org/wiki/2nd_Congress_of_the_Russian_Social_Democratic_Labour_Party',
NULL),

(1905, 1, NULL, 'First Russian Revolution', 'Bloody Sunday triggers revolution', 
'Workers spontaneously form the Soviet of Workers'' Deputies. Trotsky elected chairman.',
'revolution', 'critical', 'St. Petersburg, Russia',
ARRAY['Vladimir Lenin', 'Leon Trotsky'],
ARRAY['1905', 'soviet', 'bloody-sunday'],
'https://en.wikipedia.org/wiki/1905_Russian_Revolution',
'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/1905Demonstration.jpg/1024px-1905Demonstration.jpg'),

(1906, NULL, NULL, 'First Japanese Translation of Manifesto', 'Sakai and Kotoku translate', 
'Marxism reaches Japan via the Heimin Shimbun.',
'publication', 'normal', 'Japan',
ARRAY['Sakai Toshihiko', 'Kotoku Shusui'],
ARRAY['manifesto', 'translation', 'japan'],
'https://en.wikipedia.org/wiki/Sakai_Toshihiko',
NULL),

(1912, NULL, NULL, 'Bordiga Founds Circolo Carlo Marx', 'Opposition to Italian reformism', 
'Amadeo Bordiga opposes PSI reformism and its support for the colonial war in Libya.',
'organization', 'normal', 'Naples, Italy',
ARRAY['Amadeo Bordiga'],
ARRAY['bordiga', 'italy', 'left-communism'],
'https://en.wikipedia.org/wiki/Amadeo_Bordiga',
NULL),

(1912, 1, NULL, 'Prague Conference', 'Bolsheviks break with Mensheviks', 
'Bolsheviks formally constitute themselves as an independent party.',
'organization', 'major', 'Prague, Austria-Hungary',
ARRAY['Vladimir Lenin'],
ARRAY['bolshevik', 'prague'],
'https://en.wikipedia.org/wiki/6th_Conference_of_the_Russian_Social_Democratic_Labour_Party_(Bolsheviks)',
NULL),

(1913, NULL, NULL, 'Marxism and the National Question', 'Stalin in Vienna', 
'Stalin writes Marxism and the National Question commissioned by Lenin. Trotsky and Bukharin also in Vienna.',
'publication', 'normal', 'Vienna, Austria-Hungary',
ARRAY['Joseph Stalin', 'Vladimir Lenin'],
ARRAY['stalin', 'national-question'],
'https://en.wikipedia.org/wiki/Marxism_and_the_National_Question',
NULL),

-- ============================================
-- IV. THE GREAT RUPTURE (1914-1923)
-- ============================================

(1914, 8, 4, 'The Great Betrayal', 'SPD votes for War Credits', 
'SPD votes to fund the Kaiser''s war. Second International collapses. Lenin: "From now on, I am not a Social Democrat, I am a Communist."',
'historical', 'critical', 'Berlin, Germany',
ARRAY['Vladimir Lenin', 'Karl Kautsky'],
ARRAY['betrayal', 'war-credits', 'spd'],
'https://en.wikipedia.org/wiki/German_Social_Democratic_Party',
'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Bundesarchiv_Bild_183-R52907%2C_Berlin%2C_Mobilmachung.jpg/1024px-Bundesarchiv_Bild_183-R52907%2C_Berlin%2C_Mobilmachung.jpg'),

(1915, 9, NULL, 'Zimmerwald Conference', 'Anti-war socialists meet', 
'Lenin organizes the Zimmerwald Left: "Turn the imperialist war into civil war."',
'organization', 'major', 'Zimmerwald, Switzerland',
ARRAY['Vladimir Lenin', 'Leon Trotsky'],
ARRAY['zimmerwald', 'anti-war', 'internationalism'],
'https://en.wikipedia.org/wiki/Zimmerwald_Conference',
NULL),

(1916, 4, NULL, 'Easter Rising', 'James Connolly leads insurrection', 
'Irish Citizen Army rises against British rule. Connolly executed by firing squad.',
'revolution', 'major', 'Dublin, Ireland',
ARRAY['James Connolly'],
ARRAY['ireland', 'easter-rising', 'connolly'],
'https://en.wikipedia.org/wiki/Easter_Rising',
'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/James_Connolly2.jpg/800px-James_Connolly2.jpg'),

(1917, 2, NULL, 'February Revolution', 'The Tsar abdicates', 
'Female textile workers strike on International Women''s Day. Dual Power emerges: Provisional Government vs Petrograd Soviet.',
'revolution', 'critical', 'Petrograd, Russia',
ARRAY['Nicholas II'],
ARRAY['february', '1917', 'dual-power'],
'https://en.wikipedia.org/wiki/February_Revolution',
'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/1917petrogradsoviet_assembly.jpg/1024px-1917petrogradsoviet_assembly.jpg'),

(1917, 4, NULL, 'Lenin Returns - April Theses', 'All Power to the Soviets', 
'Lenin returns in the sealed train. Issues April Theses at Finland Station: "No support for the Provisional Government."',
'historical', 'critical', 'Petrograd, Russia',
ARRAY['Vladimir Lenin'],
ARRAY['april-theses', 'sealed-train', 'finland-station'],
'https://en.wikipedia.org/wiki/April_Theses',
'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Lenin_arrives_at_the_Finland_Station.jpg/1024px-Lenin_arrives_at_the_Finland_Station.jpg'),

(1917, 8, NULL, 'Kornilov Affair', 'Right-wing coup fails', 
'General Kornilov attempts coup. Bolsheviks organize defense, arming Red Guards.',
'historical', 'major', 'Petrograd, Russia',
ARRAY['Vladimir Lenin', 'Lavr Kornilov'],
ARRAY['kornilov', 'red-guards'],
'https://en.wikipedia.org/wiki/Kornilov_affair',
NULL),

(1917, 10, 25, 'The October Revolution', 'Dictatorship of the Proletariat established', 
'Bolsheviks seize Winter Palace. "We shall now proceed to construct the socialist order."',
'revolution', 'critical', 'Petrograd, Russia',
ARRAY['Vladimir Lenin', 'Leon Trotsky'],
ARRAY['october', '1917', 'bolshevik'],
'https://en.wikipedia.org/wiki/October_Revolution',
'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Red_Guard_Vulkan_factory.jpg/1024px-Red_Guard_Vulkan_factory.jpg'),

(1918, 1, NULL, 'Finnish Civil War', 'Reds slaughtered by Whites', 
'Social Democratic Reds crushed by Whites (Mannerheim) with German aid. 30,000 Reds die in camps.',
'war', 'major', 'Finland',
ARRAY['Carl Gustaf Mannerheim'],
ARRAY['finland', 'civil-war', 'white-terror'],
'https://en.wikipedia.org/wiki/Finnish_Civil_War',
'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Imprisoned_Finnish_Red_Guard_soldiers.jpg/1024px-Imprisoned_Finnish_Red_Guard_soldiers.jpg'),

(1918, 3, NULL, 'Treaty of Brest-Litovsk', 'Soviet Russia exits WWI', 
'Harsh peace with Germany. Lenin argues the revolution needs a "breathing space."',
'historical', 'major', 'Brest-Litovsk',
ARRAY['Vladimir Lenin', 'Leon Trotsky'],
ARRAY['brest-litovsk', 'treaty'],
'https://en.wikipedia.org/wiki/Treaty_of_Brest-Litovsk',
NULL),

(1918, 11, NULL, 'German Revolution', 'Kaiser falls, Workers'' Councils form', 
'Sailors mutiny in Kiel. Councils form across Germany. SPD takes power to stop the revolution.',
'revolution', 'critical', 'Germany',
ARRAY['Rosa Luxemburg', 'Karl Liebknecht', 'Gustav Noske'],
ARRAY['german-revolution', 'councils', 'november'],
'https://en.wikipedia.org/wiki/German_Revolution_of_1918%E2%80%931919',
'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bundesarchiv_Bild_183-B0527-0001-810%2C_Berlin%2C_Brandenburger_Tor%2C_Novemberrevolution.jpg/1024px-Bundesarchiv_Bild_183-B0527-0001-810%2C_Berlin%2C_Brandenburger_Tor%2C_Novemberrevolution.jpg'),

(1919, 1, NULL, 'Spartacist Uprising', 'Luxemburg and Liebknecht murdered', 
'KPD attempts insurrection. Rosa Luxemburg and Karl Liebknecht murdered by Freikorps. "Order reigns in Berlin!"',
'revolution', 'critical', 'Berlin, Germany',
ARRAY['Rosa Luxemburg', 'Karl Liebknecht', 'Gustav Noske'],
ARRAY['spartacist', 'luxemburg', 'liebknecht'],
'https://en.wikipedia.org/wiki/Spartacist_uprising',
'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Bundesarchiv_B_145_Bild-P046271%2C_Berlin%2C_Liebknecht%2C_Luxemburg.jpg/800px-Bundesarchiv_B_145_Bild-P046271%2C_Berlin%2C_Liebknecht%2C_Luxemburg.jpg'),

(1919, 3, NULL, 'Third International Founded', 'Comintern established', 
'Lenin founds Communist International in Moscow. The call goes out for world revolution.',
'organization', 'critical', 'Moscow, Soviet Russia',
ARRAY['Vladimir Lenin', 'Grigory Zinoviev'],
ARRAY['comintern', 'third-international'],
'https://en.wikipedia.org/wiki/Communist_International',
'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/1919_-_1._Kongress_der_Kommunistischen_Internationale.jpg/1024px-1919_-_1._Kongress_der_Kommunistischen_Internationale.jpg'),

(1919, 3, NULL, 'Hungarian Soviet Republic', '133 days of red power', 
'Béla Kun leads short-lived communist state (March-August). Falls to Romanian invasion.',
'revolution', 'major', 'Budapest, Hungary',
ARRAY['Béla Kun'],
ARRAY['hungary', 'soviet-republic'],
'https://en.wikipedia.org/wiki/Hungarian_Soviet_Republic',
'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Hungarian_Republic_of_Councils_poster.jpg/800px-Hungarian_Republic_of_Councils_poster.jpg'),

(1919, 9, NULL, 'Biennio Rosso Begins', 'Red Years in Italy', 
'Turin workers occupy Fiat factories, run them through Factory Councils. Gramsci''s L''Ordine Nuovo leads.',
'revolution', 'major', 'Turin, Italy',
ARRAY['Antonio Gramsci'],
ARRAY['biennio-rosso', 'factory-councils'],
'https://en.wikipedia.org/wiki/Biennio_Rosso',
NULL),

(1920, NULL, NULL, 'Manifesto Translated to Chinese', 'Seed for CPC planted', 
'Chen Wangdao translates in a cold shed, supposedly eating ink by mistake.',
'publication', 'major', 'China',
ARRAY['Chen Wangdao', 'Chen Duxiu'],
ARRAY['china', 'manifesto', 'translation'],
'https://en.wikipedia.org/wiki/Chen_Wangdao',
NULL),

(1920, 7, NULL, 'Second Congress of Comintern', '21 Conditions for membership', 
'Lenin presents conditions enforcing split with reformists.',
'organization', 'major', 'Moscow, Soviet Russia',
ARRAY['Vladimir Lenin'],
ARRAY['comintern', '21-conditions'],
'https://en.wikipedia.org/wiki/2nd_World_Congress_of_the_Communist_International',
NULL),

(1921, 1, NULL, 'Communist Party of Italy Founded', 'Left splits from PSI at Livorno', 
'Bordiga''s faction walks out of PSI congress singing the Internationale.',
'organization', 'major', 'Livorno, Italy',
ARRAY['Amadeo Bordiga', 'Antonio Gramsci'],
ARRAY['pcdi', 'livorno', 'bordiga'],
'https://en.wikipedia.org/wiki/Communist_Party_of_Italy',
NULL),

(1921, 3, NULL, 'Kronstadt Rebellion', 'Soviets without Bolsheviks', 
'Sailors demand "Soviets without Bolsheviks." Suppressed. Exposes contradictions of War Communism.',
'revolution', 'major', 'Kronstadt, Soviet Russia',
ARRAY['Vladimir Lenin', 'Leon Trotsky'],
ARRAY['kronstadt', 'sailors'],
'https://en.wikipedia.org/wiki/Kronstadt_rebellion',
'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Kronstadt_attack.jpg/1024px-Kronstadt_attack.jpg'),

(1921, 3, NULL, 'NEP Introduced', 'Retreat from War Communism', 
'Lenin allows limited market relations: "One step backward, two steps forward."',
'economic', 'major', 'Soviet Russia',
ARRAY['Vladimir Lenin'],
ARRAY['nep', 'war-communism'],
'https://en.wikipedia.org/wiki/New_Economic_Policy',
NULL),

(1923, 10, NULL, 'Failed German October', 'Hamburg Uprising', 
'KPD plans insurrection, called off last minute. Only Hamburg rises, is suppressed. Revolutionary wave recedes.',
'revolution', 'major', 'Hamburg, Germany',
ARRAY['Ernst Thälmann'],
ARRAY['german-october', 'hamburg'],
'https://en.wikipedia.org/wiki/Hamburg_Uprising',
'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Hamburg_Barrikade_1923.jpg/1024px-Hamburg_Barrikade_1923.jpg'),

-- ============================================
-- V. COUNTER-REVOLUTION (1924-1940)
-- ============================================

(1924, 1, 21, 'Death of Lenin', 'Power struggle begins', 
'Lenin dies at 53. Stalin promotes "Socialism in One Country," breaking with internationalism.',
'biography', 'critical', 'Gorki, Soviet Russia',
ARRAY['Vladimir Lenin', 'Joseph Stalin', 'Leon Trotsky'],
ARRAY['lenin', 'death', 'succession'],
'https://en.wikipedia.org/wiki/Vladimir_Lenin',
'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Lenin_1921_Red_Army.jpg/800px-Lenin_1921_Red_Army.jpg'),

(1926, 2, NULL, 'Bordiga Confronts Stalin', 'Russian Party must submit to International', 
'At ECCI Sixth Plenum, Bordiga declares Russian Party must be subject to International. Bordiga marginalized.',
'historical', 'major', 'Moscow, Soviet Union',
ARRAY['Amadeo Bordiga', 'Joseph Stalin'],
ARRAY['bordiga', 'stalin', 'comintern'],
'https://en.wikipedia.org/wiki/Amadeo_Bordiga',
NULL),

(1927, 4, 12, 'Shanghai Massacre', 'Chiang Kai-shek betrays United Front', 
'Thousands of communists slaughtered. Stalin''s policy of subordinating CPC to Kuomintang directly responsible.',
'historical', 'critical', 'Shanghai, China',
ARRAY['Chiang Kai-shek', 'Joseph Stalin'],
ARRAY['shanghai', 'massacre', 'china'],
'https://en.wikipedia.org/wiki/Shanghai_massacre',
'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Victims_of_the_Shanghai_massacre_1927.jpg/1024px-Victims_of_the_Shanghai_massacre_1927.jpg'),

(1928, NULL, NULL, 'Trotsky Exiled to Alma-Ata', 'Left Opposition crushed', 
'Trotsky exiled to Kazakhstan. Left Opposition crushed in USSR.',
'biography', 'major', 'Alma-Ata, Kazakhstan',
ARRAY['Leon Trotsky', 'Joseph Stalin'],
ARRAY['trotsky', 'exile', 'left-opposition'],
'https://en.wikipedia.org/wiki/Leon_Trotsky',
NULL),

(1929, NULL, NULL, 'Bukharin Removed', 'Right Opposition crushed', 
'Bukharin removed from Politburo. Stalin begins forced collectivization.',
'historical', 'major', 'Moscow, Soviet Union',
ARRAY['Nikolai Bukharin', 'Joseph Stalin'],
ARRAY['bukharin', 'right-opposition'],
'https://en.wikipedia.org/wiki/Nikolai_Bukharin',
NULL),

(1932, NULL, NULL, '1844 Manuscripts Published', 'Young Marx enters discourse', 
'Discovery and publication of Marx''s Economic and Philosophic Manuscripts. Influences Frankfurt School.',
'publication', 'major', 'Moscow/Berlin',
ARRAY['Karl Marx'],
ARRAY['1844-manuscripts', 'alienation', 'young-marx'],
'https://en.wikipedia.org/wiki/Economic_and_Philosophic_Manuscripts_of_1844',
NULL),

(1933, 1, NULL, 'Hitler Takes Power', 'KPD destroyed without a shot', 
'KPD follows "Third Period" theory, refuses united front. Strongest CP in Europe destroyed without resistance.',
'historical', 'critical', 'Berlin, Germany',
ARRAY['Adolf Hitler', 'Ernst Thälmann'],
ARRAY['hitler', 'fascism', 'kpd', 'third-period'],
'https://en.wikipedia.org/wiki/Adolf_Hitler%27s_rise_to_power',
'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Bundesarchiv_Bild_102-00089%2C_Berlin%2C_Fackelzug_zur_Machtergreifung_Hitlers.jpg/1024px-Bundesarchiv_Bild_102-00089%2C_Berlin%2C_Fackelzug_zur_Machtergreifung_Hitlers.jpg'),

(1936, 7, NULL, 'Spanish Civil War Begins', 'Workers defeat fascist coup', 
'Workers defeat Franco''s coup in Barcelona and Madrid. Anarchist and POUM militias form. ¡No pasarán!',
'war', 'critical', 'Spain',
ARRAY['Francisco Franco'],
ARRAY['spain', 'civil-war', 'anarchism'],
'https://en.wikipedia.org/wiki/Spanish_Civil_War',
'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/CNT-FAI_Militia_in_1936.jpg/1024px-CNT-FAI_Militia_in_1936.jpg'),

(1937, 5, NULL, 'May Days in Barcelona', 'Stalinists crush the revolution', 
'PSUC and Republican police crush revolution. Andreu Nin (POUM) tortured and killed by Soviet agents.',
'revolution', 'major', 'Barcelona, Spain',
ARRAY['Andreu Nin', 'George Orwell'],
ARRAY['may-days', 'barcelona', 'poum'],
'https://en.wikipedia.org/wiki/May_Days',
NULL),

(1937, NULL, NULL, 'The Great Terror', 'Old Bolsheviks liquidated', 
'Stalin liquidates Old Bolsheviks. Zinoviev, Kamenev, Bukharin executed after show trials.',
'historical', 'critical', 'Moscow, Soviet Union',
ARRAY['Joseph Stalin', 'Grigory Zinoviev', 'Nikolai Bukharin'],
ARRAY['great-terror', 'moscow-trials', 'purges'],
'https://en.wikipedia.org/wiki/Great_Purge',
NULL),

(1939, NULL, NULL, 'Grundrisse Published', 'Marx''s notebooks revealed', 
'Limited Moscow edition. Only becomes widely known in West in 1970s.',
'publication', 'major', 'Moscow, Soviet Union',
ARRAY['Karl Marx'],
ARRAY['grundrisse', 'political-economy'],
'https://en.wikipedia.org/wiki/Grundrisse',
NULL),

(1939, 4, 1, 'Franco Wins Spanish Civil War', 'Fascism triumphs', 
'Republic falls. Hundreds of thousands flee into exile.',
'war', 'major', 'Spain',
ARRAY['Francisco Franco'],
ARRAY['spain', 'franco', 'fascism'],
'https://en.wikipedia.org/wiki/Spanish_Civil_War',
NULL),

(1940, 8, 20, 'Assassination of Trotsky', 'Killed with an ice axe', 
'Ramon Mercader (NKVD) kills Trotsky in Mexico. "I am sure of the victory of the Fourth International."',
'biography', 'critical', 'Coyoacán, Mexico',
ARRAY['Leon Trotsky', 'Ramon Mercader'],
ARRAY['trotsky', 'assassination'],
'https://en.wikipedia.org/wiki/Leon_Trotsky',
'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Leon_Trotsky%2C_Mexico%2C_1940.jpg/800px-Leon_Trotsky%2C_Mexico%2C_1940.jpg'),

-- ============================================
-- VI. POST-WAR & NATIONAL LIBERATION (1945-1991)
-- ============================================

(1949, 10, 1, 'Chinese Revolution', 'Mao proclaims the People''s Republic', 
'"The Chinese people have stood up!" The peasantry surrounds the cities.',
'revolution', 'critical', 'Beijing, China',
ARRAY['Mao Zedong'],
ARRAY['china', 'prc', 'mao'],
'https://en.wikipedia.org/wiki/Chinese_Communist_Revolution',
'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Mao_proclaiming_the_establishment_of_the_PRC_in_1949.jpg/1024px-Mao_proclaiming_the_establishment_of_the_PRC_in_1949.jpg'),

(1952, NULL, NULL, 'Bordiga''s Dialogue with Stalin', 'Proving USSR is capitalist', 
'Bordiga proves USSR is capitalist: wage, money, commodity exchange remain.',
'publication', 'major', 'Italy',
ARRAY['Amadeo Bordiga'],
ARRAY['bordiga', 'state-capitalism', 'ussr'],
'https://en.wikipedia.org/wiki/Amadeo_Bordiga',
NULL),

(1956, 10, NULL, 'Hungarian Revolution', 'Workers councils against Soviet bureaucracy', 
'Workers demand "Socialism without Russians." Crushed by Soviet tanks. 2,500 die.',
'revolution', 'major', 'Budapest, Hungary',
ARRAY['Imre Nagy'],
ARRAY['hungary', '1956', 'workers-councils'],
'https://en.wikipedia.org/wiki/Hungarian_Revolution_of_1956',
'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Hole_in_flag_-_Loss_of_Communism.jpg/800px-Hole_in_flag_-_Loss_of_Communism.jpg'),

(1959, 1, 1, 'Cuban Revolution', 'Castro enters Havana', 
'26th of July Movement triumphs. Batista flees. Socialism 90 miles from USA.',
'revolution', 'critical', 'Havana, Cuba',
ARRAY['Fidel Castro', 'Che Guevara'],
ARRAY['cuba', 'revolution', 'castro'],
'https://en.wikipedia.org/wiki/Cuban_Revolution',
'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/CheyFidel.jpg/800px-CheyFidel.jpg'),

(1961, 1, 17, 'Assassination of Patrice Lumumba', 'Hope of African independence murdered', 
'CIA and Belgium eliminate Congo''s democratically elected leader.',
'historical', 'major', 'Katanga, Congo',
ARRAY['Patrice Lumumba'],
ARRAY['lumumba', 'congo', 'cia', 'africa'],
'https://en.wikipedia.org/wiki/Patrice_Lumumba',
'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Patrice_Lumumba_official_portrait.jpg/800px-Patrice_Lumumba_official_portrait.jpg'),

(1966, NULL, NULL, 'Cultural Revolution Begins', 'Mao mobilizes Red Guards', 
'"Bombard the Headquarters!" Chaotic attempt to purge rivals. "To rebel is justified!"',
'historical', 'major', 'China',
ARRAY['Mao Zedong'],
ARRAY['cultural-revolution', 'red-guards', 'china'],
'https://en.wikipedia.org/wiki/Cultural_Revolution',
'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/1967-01_1967%E5%B9%B4%E5%A4%A9%E5%AE%89%E9%97%A8%E5%B9%BF%E5%9C%BA%E6%B8%B8%E8%A1%8C.jpg/1024px-1967-01_1967%E5%B9%B4%E5%A4%A9%E5%AE%89%E9%97%A8%E5%B9%BF%E5%9C%BA%E6%B8%B8%E8%A1%8C.jpg'),

(1968, 5, NULL, 'May ''68 in France', '10 million workers on general strike', 
'"Be realistic, demand the impossible!" PCF helps de-escalate strike to save Gaullist state.',
'revolution', 'major', 'Paris, France',
ARRAY['Daniel Cohn-Bendit'],
ARRAY['may-68', 'france', 'general-strike'],
'https://en.wikipedia.org/wiki/May_68',
'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Barricade_Paris_1968.jpg/1024px-Barricade_Paris_1968.jpg'),

(1975, 4, 30, 'Fall of Saigon', 'US imperialism defeated', 
'Vietnam unified. Most powerful military defeated by peasant army.',
'historical', 'major', 'Saigon, Vietnam',
ARRAY['Ho Chi Minh'],
ARRAY['vietnam', 'saigon', 'anti-imperialism'],
'https://en.wikipedia.org/wiki/Fall_of_Saigon',
'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Saigon-hubert-van-es.jpg/1024px-Saigon-hubert-van-es.jpg'),

(1976, NULL, NULL, 'Cambodian Genocide', 'Khmer Rouge''s Year Zero', 
'Pol Pot attempts agrarian utopia by emptying cities. 1.5-2 million die.',
'historical', 'major', 'Cambodia',
ARRAY['Pol Pot'],
ARRAY['cambodia', 'khmer-rouge', 'genocide'],
'https://en.wikipedia.org/wiki/Cambodian_genocide',
'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Tuol_Sleng_-_Prisoners.jpg/1024px-Tuol_Sleng_-_Prisoners.jpg'),

(1987, 10, 15, 'Assassination of Thomas Sankara', 'Africa''s Che Guevara murdered', 
'Killed by deputy Blaise Compaoré (backed by France). The "Upright Man" eliminated.',
'biography', 'major', 'Ouagadougou, Burkina Faso',
ARRAY['Thomas Sankara', 'Blaise Compaoré'],
ARRAY['sankara', 'burkina-faso', 'africa'],
'https://en.wikipedia.org/wiki/Thomas_Sankara',
'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Thomas_Sankara.jpg/800px-Thomas_Sankara.jpg'),

(1991, 12, 26, 'Dissolution of the USSR', 'Red flag lowered over Kremlin', 
'Russian state-capitalist experiment ends. Transitions to private bandit-capitalism.',
'historical', 'critical', 'Moscow, Russia',
ARRAY['Mikhail Gorbachev', 'Boris Yeltsin'],
ARRAY['ussr', 'dissolution', 'cold-war'],
'https://en.wikipedia.org/wiki/Dissolution_of_the_Soviet_Union',
'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/RIAN_archive_848095_Gorbachev_signing_law_on_ending_the_USSR.jpg/1024px-RIAN_archive_848095_Gorbachev_signing_law_on_ending_the_USSR.jpg');
