-- Timeline Events Part 3: The Great Rupture (1914-1923)

INSERT INTO timeline_events (year, month, day, title, description, detailed_description, category, importance, location, related_people, tags, wikipedia_url, image_url) VALUES

(1914, 8, 4, 'The Great Betrayal', 'SPD votes for War Credits', 
'SPD votes to fund the Kaiser''s war. Second International collapses into social-chauvinism. Lenin: "From now on, I am not a Social Democrat, I am a Communist."',
'historical', 'critical', 'Berlin, Germany',
ARRAY['Vladimir Lenin', 'Karl Kautsky'],
ARRAY['betrayal', 'war-credits', 'spd'],
'https://en.wikipedia.org/wiki/German_Social_Democratic_Party',
'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Bundesarchiv_Bild_183-R52907%2C_Berlin%2C_Mobilmachung.jpg/1024px-Bundesarchiv_Bild_183-R52907%2C_Berlin%2C_Mobilmachung.jpg'),

(1915, 9, NULL, 'Zimmerwald Conference', 'Anti-war socialists meet', 
'Lenin organizes the Zimmerwald Left: "Turn the imperialist war into civil war." The nucleus of the Third International forms.',
'organization', 'major', 'Zimmerwald, Switzerland',
ARRAY['Vladimir Lenin', 'Leon Trotsky'],
ARRAY['zimmerwald', 'anti-war', 'internationalism'],
'https://en.wikipedia.org/wiki/Zimmerwald_Conference',
NULL),

(1916, 4, NULL, 'Easter Rising', 'James Connolly leads insurrection', 
'Irish Citizen Army rises against British rule. Connolly executed by firing squad. Lenin defends the rising against dogmatists.',
'revolution', 'major', 'Dublin, Ireland',
ARRAY['James Connolly'],
ARRAY['ireland', 'easter-rising', 'connolly'],
'https://en.wikipedia.org/wiki/Easter_Rising',
'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/James_Connolly2.jpg/800px-James_Connolly2.jpg'),

(1917, 2, NULL, 'February Revolution', 'The Tsar abdicates', 
'Female textile workers strike on International Women''s Day. Tsar abdicates. Dual Power emerges: Provisional Government vs Petrograd Soviet.',
'revolution', 'critical', 'Petrograd, Russia',
ARRAY['Nicholas II'],
ARRAY['february', '1917', 'dual-power'],
'https://en.wikipedia.org/wiki/February_Revolution',
'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/1917petrogradsoviet_assembly.jpg/1024px-1917petrogradsoviet_assembly.jpg'),

(1917, 4, NULL, 'Lenin Returns - April Theses', 'All Power to the Soviets', 
'Lenin returns in the sealed train. Issues April Theses at Finland Station: "No support for the Provisional Government." Bolsheviks realign toward socialist revolution.',
'historical', 'critical', 'Petrograd, Russia',
ARRAY['Vladimir Lenin'],
ARRAY['april-theses', 'sealed-train', 'finland-station'],
'https://en.wikipedia.org/wiki/April_Theses',
'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Lenin_arrives_at_the_Finland_Station.jpg/1024px-Lenin_arrives_at_the_Finland_Station.jpg'),

(1917, 8, NULL, 'Kornilov Affair', 'Right-wing coup fails', 
'General Kornilov attempts coup. Bolsheviks organize defense, arming Red Guards. Their popularity surges.',
'historical', 'major', 'Petrograd, Russia',
ARRAY['Vladimir Lenin', 'Lavr Kornilov'],
ARRAY['kornilov', 'red-guards'],
'https://en.wikipedia.org/wiki/Kornilov_affair',
NULL),

(1917, 10, 25, 'The October Revolution', 'Dictatorship of the Proletariat established', 
'Bolsheviks seize Winter Palace. Second Congress of Soviets ratifies transfer of power. "We shall now proceed to construct the socialist order."',
'revolution', 'critical', 'Petrograd, Russia',
ARRAY['Vladimir Lenin', 'Leon Trotsky'],
ARRAY['october', '1917', 'bolshevik'],
'https://en.wikipedia.org/wiki/October_Revolution',
'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Red_Guard_Vulkan_factory.jpg/1024px-Red_Guard_Vulkan_factory.jpg'),

(1918, 1, NULL, 'Finnish Civil War', 'Reds slaughtered by Whites', 
'Social Democratic Reds crushed by Whites (Mannerheim) with German aid. 30,000 Reds die in camps.',
'war', 'major', 'Finland',
ARRAY['Carl Gustaf Mannerheim'],
ARRAY['finland', 'civil-war', 'white-terror'],
'https://en.wikipedia.org/wiki/Finnish_Civil_War',
'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Imprisoned_Finnish_Red_Guard_soldiers.jpg/1024px-Imprisoned_Finnish_Red_Guard_soldiers.jpg'),

(1918, 3, NULL, 'Treaty of Brest-Litovsk', 'Soviet Russia exits WWI', 
'Harsh peace with Germany. Left SRs revolt. Lenin argues the revolution needs a "breathing space."',
'historical', 'major', 'Brest-Litovsk',
ARRAY['Vladimir Lenin', 'Leon Trotsky'],
ARRAY['brest-litovsk', 'treaty'],
'https://en.wikipedia.org/wiki/Treaty_of_Brest-Litovsk',
NULL),

(1918, 11, NULL, 'German Revolution', 'Kaiser falls, Workers'' Councils form', 
'Sailors mutiny in Kiel. Councils form across Germany. SPD takes power to stop the revolution. Noske: "Someone must be the bloodhound."',
'revolution', 'critical', 'Germany',
ARRAY['Rosa Luxemburg', 'Karl Liebknecht', 'Gustav Noske'],
ARRAY['german-revolution', 'councils', 'november'],
'https://en.wikipedia.org/wiki/German_Revolution_of_1918%E2%80%931919',
'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bundesarchiv_Bild_183-B0527-0001-810%2C_Berlin%2C_Brandenburger_Tor%2C_Novemberrevolution.jpg/1024px-Bundesarchiv_Bild_183-B0527-0001-810%2C_Berlin%2C_Brandenburger_Tor%2C_Novemberrevolution.jpg'),

(1919, 1, NULL, 'Spartacist Uprising', 'Luxemburg and Liebknecht murdered', 
'KPD attempts insurrection. Rosa Luxemburg and Karl Liebknecht murdered by Freikorps on orders of SPD Minister Noske. "Order reigns in Berlin!"',
'revolution', 'critical', 'Berlin, Germany',
ARRAY['Rosa Luxemburg', 'Karl Liebknecht', 'Gustav Noske'],
ARRAY['spartacist', 'luxemburg', 'liebknecht'],
'https://en.wikipedia.org/wiki/Spartacist_uprising',
'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Bundesarchiv_B_145_Bild-P046271%2C_Berlin%2C_Liebknecht%2C_Luxemburg.jpg/800px-Bundesarchiv_B_145_Bild-P046271%2C_Berlin%2C_Liebknecht%2C_Luxemburg.jpg'),

(1919, 3, NULL, 'Third International Founded', 'Comintern established', 
'Lenin founds Communist International in Moscow. The call goes out for world revolution.',
'organization', 'critical', 'Moscow, Soviet Russia',
ARRAY['Vladimir Lenin', 'Grigory Zinoviev'],
ARRAY['comintern', 'third-international'],
'https://en.wikipedia.org/wiki/Communist_International',
'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/1919_-_1._Kongress_der_Kommunistischen_Internationale.jpg/1024px-1919_-_1._Kongress_der_Kommunistischen_Internationale.jpg'),

(1919, 3, NULL, 'Hungarian Soviet Republic', '133 days of red power', 
'Béla Kun leads short-lived communist state (March-August). Falls to Romanian invasion.',
'revolution', 'major', 'Budapest, Hungary',
ARRAY['Béla Kun'],
ARRAY['hungary', 'soviet-republic'],
'https://en.wikipedia.org/wiki/Hungarian_Soviet_Republic',
'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Hungarian_Republic_of_Councils_poster.jpg/800px-Hungarian_Republic_of_Councils_poster.jpg'),

(1919, 9, NULL, 'Biennio Rosso Begins', 'Red Years in Italy', 
'Turin workers occupy Fiat factories, run them through Factory Councils. Gramsci''s L''Ordine Nuovo leads.',
'revolution', 'major', 'Turin, Italy',
ARRAY['Antonio Gramsci'],
ARRAY['biennio-rosso', 'factory-councils'],
'https://en.wikipedia.org/wiki/Biennio_Rosso',
NULL),

(1920, NULL, NULL, 'Manifesto Translated to Chinese', 'Seed for CPC planted', 
'Chen Wangdao translates in a cold shed, supposedly eating ink by mistake. Chen Duxiu leads early communist organizing.',
'publication', 'major', 'China',
ARRAY['Chen Wangdao', 'Chen Duxiu'],
ARRAY['china', 'manifesto', 'translation'],
'https://en.wikipedia.org/wiki/Chen_Wangdao',
NULL),

(1920, 7, NULL, 'Second Congress of Comintern', '21 Conditions for membership', 
'Lenin presents conditions enforcing split with reformists. Comintern defines itself against social democracy.',
'organization', 'major', 'Moscow, Soviet Russia',
ARRAY['Vladimir Lenin'],
ARRAY['comintern', '21-conditions'],
'https://en.wikipedia.org/wiki/2nd_World_Congress_of_the_Communist_International',
NULL),

(1921, 1, NULL, 'Communist Party of Italy Founded', 'Left splits from PSI at Livorno', 
'Bordiga''s faction walks out of PSI congress singing the Internationale. Italian Comintern section born.',
'organization', 'major', 'Livorno, Italy',
ARRAY['Amadeo Bordiga', 'Antonio Gramsci'],
ARRAY['pcdi', 'livorno', 'bordiga'],
'https://en.wikipedia.org/wiki/Communist_Party_of_Italy',
NULL),

(1921, 3, NULL, 'Kronstadt Rebellion', 'Soviets without Bolsheviks', 
'Sailors demand "Soviets without Bolsheviks." Suppressed. Exposes contradictions of War Communism.',
'revolution', 'major', 'Kronstadt, Soviet Russia',
ARRAY['Vladimir Lenin', 'Leon Trotsky'],
ARRAY['kronstadt', 'sailors'],
'https://en.wikipedia.org/wiki/Kronstadt_rebellion',
'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Kronstadt_attack.jpg/1024px-Kronstadt_attack.jpg'),

(1921, 3, NULL, 'NEP Introduced', 'Retreat from War Communism', 
'Lenin allows limited market relations: "One step backward, two steps forward."',
'economic', 'major', 'Soviet Russia',
ARRAY['Vladimir Lenin'],
ARRAY['nep', 'war-communism'],
'https://en.wikipedia.org/wiki/New_Economic_Policy',
NULL),

(1923, 10, NULL, 'Failed German October', 'Hamburg Uprising', 
'KPD plans insurrection, called off last minute. Only Hamburg rises, is suppressed. Revolutionary wave recedes.',
'revolution', 'major', 'Hamburg, Germany',
ARRAY['Ernst Thälmann'],
ARRAY['german-october', 'hamburg'],
'https://en.wikipedia.org/wiki/Hamburg_Uprising',
'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Hamburg_Barrikade_1923.jpg/1024px-Hamburg_Barrikade_1923.jpg');
