-- Timeline Events Part 4: The Counter-Revolution (1924-1940)

INSERT INTO timeline_events (year, month, day, title, description, detailed_description, category, importance, location, related_people, tags, wikipedia_url, image_url) VALUES

(1924, 1, 21, 'Death of Lenin', 'Power struggle begins', 
'Lenin dies at 53 after strokes. Stalin promotes "Socialism in One Country," breaking with internationalism. Body placed in mausoleum.',
'biography', 'critical', 'Gorki, Soviet Russia',
ARRAY['Vladimir Lenin', 'Joseph Stalin', 'Leon Trotsky'],
ARRAY['lenin', 'death', 'succession'],
'https://en.wikipedia.org/wiki/Vladimir_Lenin',
'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Lenin_1921_Red_Army.jpg/800px-Lenin_1921_Red_Army.jpg'),

(1926, 2, NULL, 'Bordiga Confronts Stalin', 'Russian Party must submit to International', 
'At ECCI Sixth Plenum, Bordiga declares Russian Party must be subject to International, not vice versa. Bordiga marginalized.',
'historical', 'major', 'Moscow, Soviet Union',
ARRAY['Amadeo Bordiga', 'Joseph Stalin'],
ARRAY['bordiga', 'stalin', 'comintern'],
'https://en.wikipedia.org/wiki/Amadeo_Bordiga',
NULL),

(1927, 4, 12, 'Shanghai Massacre', 'Chiang Kai-shek betrays United Front', 
'Thousands of communists slaughtered. Stalin''s policy of subordinating CPC to Kuomintang directly responsible.',
'historical', 'critical', 'Shanghai, China',
ARRAY['Chiang Kai-shek', 'Joseph Stalin'],
ARRAY['shanghai', 'massacre', 'china'],
'https://en.wikipedia.org/wiki/Shanghai_massacre',
'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Victims_of_the_Shanghai_massacre_1927.jpg/1024px-Victims_of_the_Shanghai_massacre_1927.jpg'),

(1928, NULL, NULL, 'Trotsky Exiled to Alma-Ata', 'Left Opposition crushed', 
'Trotsky exiled to Kazakhstan. Left Opposition crushed in USSR. Next year expelled entirely.',
'biography', 'major', 'Alma-Ata, Kazakhstan',
ARRAY['Leon Trotsky', 'Joseph Stalin'],
ARRAY['trotsky', 'exile', 'left-opposition'],
'https://en.wikipedia.org/wiki/Leon_Trotsky',
NULL),

(1929, NULL, NULL, 'Bukharin Removed', 'Right Opposition crushed', 
'Bukharin removed from Politburo. Right Opposition crushed. Stalin begins forced collectivization.',
'historical', 'major', 'Moscow, Soviet Union',
ARRAY['Nikolai Bukharin', 'Joseph Stalin'],
ARRAY['bukharin', 'right-opposition'],
'https://en.wikipedia.org/wiki/Nikolai_Bukharin',
NULL),

(1932, NULL, NULL, '1844 Manuscripts Published', 'Young Marx enters discourse', 
'Discovery and publication of Marx''s Economic and Philosophic Manuscripts. "Young Marx" (Humanism/Alienation) influences Frankfurt School.',
'publication', 'major', 'Moscow/Berlin',
ARRAY['Karl Marx'],
ARRAY['1844-manuscripts', 'alienation', 'young-marx'],
'https://en.wikipedia.org/wiki/Economic_and_Philosophic_Manuscripts_of_1844',
NULL),

(1933, 1, NULL, 'Hitler Takes Power', 'KPD destroyed without a shot', 
'Hitler takes power. KPD follows Stalin''s "Third Period" theory, refuses united front with SPD. Strongest CP in Europe destroyed without resistance.',
'historical', 'critical', 'Berlin, Germany',
ARRAY['Adolf Hitler', 'Ernst Thälmann'],
ARRAY['hitler', 'fascism', 'kpd', 'third-period'],
'https://en.wikipedia.org/wiki/Adolf_Hitler%27s_rise_to_power',
'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Bundesarchiv_Bild_102-00089%2C_Berlin%2C_Fackelzug_zur_Machtergreifung_Hitlers.jpg/1024px-Bundesarchiv_Bild_102-00089%2C_Berlin%2C_Fackelzug_zur_Machtergreifung_Hitlers.jpg'),

(1936, 7, NULL, 'Spanish Civil War Begins', 'Workers defeat fascist coup', 
'Workers defeat Franco''s coup in Barcelona and Madrid. Anarchist and POUM militias form. ¡No pasarán!',
'war', 'critical', 'Spain',
ARRAY['Francisco Franco'],
ARRAY['spain', 'civil-war', 'anarchism'],
'https://en.wikipedia.org/wiki/Spanish_Civil_War',
'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/CNT-FAI_Militia_in_1936.jpg/1024px-CNT-FAI_Militia_in_1936.jpg'),

(1937, 5, NULL, 'May Days in Barcelona', 'Stalinists crush the revolution', 
'PSUC and Republican police crush revolution. Andreu Nin (POUM) tortured and killed by Soviet agents. Orwell narrowly escapes.',
'revolution', 'major', 'Barcelona, Spain',
ARRAY['Andreu Nin', 'George Orwell'],
ARRAY['may-days', 'barcelona', 'poum'],
'https://en.wikipedia.org/wiki/May_Days',
NULL),

(1937, NULL, NULL, 'The Great Terror', 'Old Bolsheviks liquidated', 
'Stalin liquidates Old Bolsheviks. Zinoviev, Kamenev, Bukharin executed after show trials. Red Army decimated (Tukhachevsky).',
'historical', 'critical', 'Moscow, Soviet Union',
ARRAY['Joseph Stalin', 'Grigory Zinoviev', 'Nikolai Bukharin'],
ARRAY['great-terror', 'moscow-trials', 'purges'],
'https://en.wikipedia.org/wiki/Great_Purge',
NULL),

(1939, NULL, NULL, 'Grundrisse Published', 'Marx''s notebooks revealed', 
'Limited Moscow edition. Only becomes widely known in West in 1970s. Revolutionizes understanding of Marx''s value theory.',
'publication', 'major', 'Moscow, Soviet Union',
ARRAY['Karl Marx'],
ARRAY['grundrisse', 'political-economy'],
'https://en.wikipedia.org/wiki/Grundrisse',
NULL),

(1939, 4, 1, 'Franco Wins Spanish Civil War', 'Fascism triumphs', 
'Republic falls. Hundreds of thousands flee into exile. Revolution definitively crushed.',
'war', 'major', 'Spain',
ARRAY['Francisco Franco'],
ARRAY['spain', 'franco', 'fascism'],
'https://en.wikipedia.org/wiki/Spanish_Civil_War',
NULL),

(1940, 8, 20, 'Assassination of Trotsky', 'Killed with an ice axe', 
'Ramon Mercader (NKVD) kills Trotsky in Mexico. Last major Old Bolshevik eliminated. "I am sure of the victory of the Fourth International."',
'biography', 'critical', 'Coyoacán, Mexico',
ARRAY['Leon Trotsky', 'Ramon Mercader'],
ARRAY['trotsky', 'assassination'],
'https://en.wikipedia.org/wiki/Leon_Trotsky',
'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Leon_Trotsky%2C_Mexico%2C_1940.jpg/800px-Leon_Trotsky%2C_Mexico%2C_1940.jpg');
