-- Timeline Events Part 2: Age of Imperialism & Second International (1875-1914)

INSERT INTO timeline_events (year, month, day, title, description, detailed_description, category, importance, location, related_people, tags, wikipedia_url, image_url) VALUES

(1875, NULL, NULL, 'Gotha Congress', 'Marx attacks reformist slogans', 
'Marxists merge with Lassalleans to form SAPD (later SPD). Marx writes Critique of the Gotha Programme attacking "free state" and "fair wage" slogans.',
'organization', 'major', 'Gotha, Germany',
ARRAY['Karl Marx', 'Ferdinand Lassalle'],
ARRAY['gotha', 'spd', 'critique'],
'https://en.wikipedia.org/wiki/Critique_of_the_Gotha_Programme',
NULL),

(1882, NULL, NULL, 'First Russian Translation of Manifesto', 'Plekhanov translates the Manifesto', 
'In the preface, Marx speculates if the Russian Obshchina (peasant commune) can skip capitalism - he says yes, if supported by a Western revolution.',
'publication', 'normal', 'Geneva, Switzerland',
ARRAY['Georgi Plekhanov', 'Karl Marx'],
ARRAY['manifesto', 'translation', 'russia'],
'https://en.wikipedia.org/wiki/Georgi_Plekhanov',
NULL),

(1886, 5, 4, 'Haymarket Affair', 'Origin of May Day', 
'Anarchist bombing and police riot lead to execution of labor leaders. Becomes origin of International Workers'' Day.',
'historical', 'major', 'Chicago, USA',
ARRAY['Albert Parsons', 'August Spies'],
ARRAY['haymarket', 'may-day', 'labor'],
'https://en.wikipedia.org/wiki/Haymarket_affair',
'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Haymarket_Riot-Harpers_Weekly.jpg/1024px-Haymarket_Riot-Harpers_Weekly.jpg'),

(1887, NULL, NULL, 'First English Capital', 'Moore/Aveling translation', 
'First English translation of Capital Vol I, supervised by Engels. Marx''s critique reaches the Anglophone world.',
'publication', 'normal', 'London, England',
ARRAY['Karl Marx', 'Friedrich Engels'],
ARRAY['capital', 'translation'],
'https://en.wikipedia.org/wiki/Das_Kapital',
NULL),

(1889, 7, 14, 'Second International Founded', 'Socialist parties unite globally', 
'Founded on the centenary of the French Revolution. Adopts May 1st as global demonstration day.',
'organization', 'major', 'Paris, France',
ARRAY['Friedrich Engels'],
ARRAY['second-international', 'may-day'],
'https://en.wikipedia.org/wiki/Second_International',
NULL),

(1891, NULL, NULL, 'Erfurt Program', 'SPD adopts Marxist program', 
'Written by Kautsky, but separates "maximum program" (revolution) from "minimum program" (reforms), seeding future betrayal.',
'organization', 'normal', 'Erfurt, Germany',
ARRAY['Karl Kautsky'],
ARRAY['erfurt', 'spd', 'program'],
'https://en.wikipedia.org/wiki/Erfurt_Program',
NULL),

(1898, NULL, NULL, 'RSDLP Founded', 'Russian Social Democratic Labour Party', 
'Founded in Minsk in a small wooden house. Most delegates arrested shortly after. The party of October is born.',
'organization', 'major', 'Minsk, Russian Empire',
ARRAY['Vladimir Lenin'],
ARRAY['rsdlp', 'russia'],
'https://en.wikipedia.org/wiki/Russian_Social_Democratic_Labour_Party',
NULL),

(1902, NULL, NULL, 'What Is To Be Done?', 'Theory of the vanguard party', 
'Lenin argues against Economism. Revolutionary consciousness must be brought to the class by a vanguard party of professional revolutionaries.',
'publication', 'critical', 'Stuttgart, Germany',
ARRAY['Vladimir Lenin'],
ARRAY['lenin', 'vanguard', 'party'],
'https://en.wikipedia.org/wiki/What_Is_to_Be_Done%3F',
NULL),

(1903, 7, NULL, 'Bolshevik-Menshevik Split', 'Split over party organization', 
'At the Second Congress in London/Brussels, party splits between Bolsheviks (Lenin) and Mensheviks (Martov) over definition of party membership.',
'organization', 'critical', 'London/Brussels',
ARRAY['Vladimir Lenin', 'Julius Martov'],
ARRAY['bolshevik', 'menshevik', 'split'],
'https://en.wikipedia.org/wiki/2nd_Congress_of_the_Russian_Social_Democratic_Labour_Party',
NULL),

(1905, 1, NULL, 'First Russian Revolution', 'Bloody Sunday triggers revolution', 
'Workers spontaneously form the Soviet of Workers'' Deputies. Trotsky elected chairman. Lenin writes Two Tactics of Social-Democracy.',
'revolution', 'critical', 'St. Petersburg, Russia',
ARRAY['Vladimir Lenin', 'Leon Trotsky'],
ARRAY['1905', 'soviet', 'bloody-sunday'],
'https://en.wikipedia.org/wiki/1905_Russian_Revolution',
'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/1905Demonstration.jpg/1024px-1905Demonstration.jpg'),

(1906, NULL, NULL, 'First Japanese Translation of Manifesto', 'Sakai and Kotoku translate', 
'Sakai Toshihiko and Kotoku Shusui translate the Manifesto in the Heimin Shimbun. Marxism reaches Japan.',
'publication', 'normal', 'Japan',
ARRAY['Sakai Toshihiko', 'Kotoku Shusui'],
ARRAY['manifesto', 'translation', 'japan'],
'https://en.wikipedia.org/wiki/Sakai_Toshihiko',
NULL),

(1912, NULL, NULL, 'Bordiga Founds Circolo Carlo Marx', 'Opposition to Italian reformism', 
'Amadeo Bordiga opposes PSI reformism and its support for the colonial war in Libya.',
'organization', 'normal', 'Naples, Italy',
ARRAY['Amadeo Bordiga'],
ARRAY['bordiga', 'italy', 'left-communism'],
'https://en.wikipedia.org/wiki/Amadeo_Bordiga',
NULL),

(1912, 1, NULL, 'Prague Conference', 'Bolsheviks break with Mensheviks', 
'Bolsheviks formally constitute themselves as an independent party. The organizational basis for October is laid.',
'organization', 'major', 'Prague, Austria-Hungary',
ARRAY['Vladimir Lenin'],
ARRAY['bolshevik', 'prague'],
'https://en.wikipedia.org/wiki/6th_Conference_of_the_Russian_Social_Democratic_Labour_Party_(Bolsheviks)',
NULL),

(1913, NULL, NULL, 'Marxism and the National Question', 'Stalin in Vienna', 
'Stalin visits Vienna, writes Marxism and the National Question commissioned by Lenin. Trotsky and Bukharin also in Vienna.',
'publication', 'normal', 'Vienna, Austria-Hungary',
ARRAY['Joseph Stalin', 'Vladimir Lenin'],
ARRAY['stalin', 'national-question'],
'https://en.wikipedia.org/wiki/Marxism_and_the_National_Question',
NULL);
