-- Timeline Events Part 5: Post-War & National Liberation (1945-1991)

INSERT INTO timeline_events (year, month, day, title, description, detailed_description, category, importance, location, related_people, tags, wikipedia_url, image_url) VALUES

(1949, 10, 1, 'Chinese Revolution', 'Mao proclaims the People''s Republic', 
'"The Chinese people have stood up!" The peasantry surrounds the cities in the world''s largest revolution.',
'revolution', 'critical', 'Beijing, China',
ARRAY['Mao Zedong'],
ARRAY['china', 'prc', 'mao'],
'https://en.wikipedia.org/wiki/Chinese_Communist_Revolution',
'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Mao_proclaiming_the_establishment_of_the_PRC_in_1949.jpg/1024px-Mao_proclaiming_the_establishment_of_the_PRC_in_1949.jpg'),

(1952, NULL, NULL, 'Bordiga''s Dialogue with Stalin', 'Proving USSR is capitalist', 
'Bordiga writes Species and Individual, Economic and Social Structure of Russia. Proves USSR is capitalist: wage, money, commodity exchange remain.',
'publication', 'major', 'Italy',
ARRAY['Amadeo Bordiga'],
ARRAY['bordiga', 'state-capitalism', 'ussr'],
'https://en.wikipedia.org/wiki/Amadeo_Bordiga',
NULL),

(1956, 10, NULL, 'Hungarian Revolution', 'Workers councils against Soviet bureaucracy', 
'Workers demand "Socialism without Russians." Crushed by Soviet tanks. 2,500 Hungarians die defending the revolution.',
'revolution', 'major', 'Budapest, Hungary',
ARRAY['Imre Nagy'],
ARRAY['hungary', '1956', 'workers-councils'],
'https://en.wikipedia.org/wiki/Hungarian_Revolution_of_1956',
'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Hole_in_flag_-_Loss_of_Communism.jpg/800px-Hole_in_flag_-_Loss_of_Communism.jpg'),

(1959, 1, 1, 'Cuban Revolution', 'Castro enters Havana', 
'26th of July Movement triumphs. Batista flees. Socialism established 90 miles from USA.',
'revolution', 'critical', 'Havana, Cuba',
ARRAY['Fidel Castro', 'Che Guevara'],
ARRAY['cuba', 'revolution', 'castro'],
'https://en.wikipedia.org/wiki/Cuban_Revolution',
'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/CheyFidel.jpg/800px-CheyFidel.jpg'),

(1961, 1, 17, 'Assassination of Patrice Lumumba', 'Hope of African independence murdered', 
'CIA and Belgium eliminate Congo''s democratically elected leader. Lumumba becomes martyr of anti-imperialism.',
'historical', 'major', 'Katanga, Congo',
ARRAY['Patrice Lumumba'],
ARRAY['lumumba', 'congo', 'cia', 'africa'],
'https://en.wikipedia.org/wiki/Patrice_Lumumba',
'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Patrice_Lumumba_official_portrait.jpg/800px-Patrice_Lumumba_official_portrait.jpg'),

(1966, NULL, NULL, 'Cultural Revolution Begins', 'Mao mobilizes Red Guards', 
'"Bombard the Headquarters!" Chaotic attempt to purge rivals and manage contradictions of state capitalism. "To rebel is justified!"',
'historical', 'major', 'China',
ARRAY['Mao Zedong'],
ARRAY['cultural-revolution', 'red-guards', 'china'],
'https://en.wikipedia.org/wiki/Cultural_Revolution',
'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/1967-01_1967%E5%B9%B4%E5%A4%A9%E5%AE%89%E9%97%A8%E5%B9%BF%E5%9C%BA%E6%B8%B8%E8%A1%8C.jpg/1024px-1967-01_1967%E5%B9%B4%E5%A4%A9%E5%AE%89%E9%97%A8%E5%B9%BF%E5%9C%BA%E6%B8%B8%E8%A1%8C.jpg'),

(1968, 5, NULL, 'May ''68 in France', '10 million workers on general strike', 
'Students occupy Sorbonne. "Be realistic, demand the impossible!" PCF helps de-escalate strike to save Gaullist state.',
'revolution', 'major', 'Paris, France',
ARRAY['Daniel Cohn-Bendit'],
ARRAY['may-68', 'france', 'general-strike'],
'https://en.wikipedia.org/wiki/May_68',
'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Barricade_Paris_1968.jpg/1024px-Barricade_Paris_1968.jpg'),

(1975, 4, 30, 'Fall of Saigon', 'US imperialism defeated', 
'Vietnam unified after decades of war. Most powerful military defeated by peasant army.',
'historical', 'major', 'Saigon, Vietnam',
ARRAY['Ho Chi Minh'],
ARRAY['vietnam', 'saigon', 'anti-imperialism'],
'https://en.wikipedia.org/wiki/Fall_of_Saigon',
'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Saigon-hubert-van-es.jpg/1024px-Saigon-hubert-van-es.jpg'),

(1976, NULL, NULL, 'Cambodian Genocide', 'Khmer Rouge''s Year Zero', 
'Pol Pot attempts primitive agrarian utopia by emptying cities. 1.5-2 million die. Distorted Maoism mixed with French existentialism.',
'historical', 'major', 'Cambodia',
ARRAY['Pol Pot'],
ARRAY['cambodia', 'khmer-rouge', 'genocide'],
'https://en.wikipedia.org/wiki/Cambodian_genocide',
'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Tuol_Sleng_-_Prisoners.jpg/1024px-Tuol_Sleng_-_Prisoners.jpg'),

(1987, 10, 15, 'Assassination of Thomas Sankara', 'Africa''s Che Guevara murdered', 
'Killed by deputy Blaise Compaoré (backed by France). The "Upright Man" who vaccinated 2.5 million children in a week is eliminated.',
'biography', 'major', 'Ouagadougou, Burkina Faso',
ARRAY['Thomas Sankara', 'Blaise Compaoré'],
ARRAY['sankara', 'burkina-faso', 'africa'],
'https://en.wikipedia.org/wiki/Thomas_Sankara',
'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Thomas_Sankara.jpg/800px-Thomas_Sankara.jpg'),

(1991, 12, 26, 'Dissolution of the USSR', 'Red flag lowered over Kremlin', 
'Russian state-capitalist experiment ends. Transitions to private bandit-capitalism. End of an era.',
'historical', 'critical', 'Moscow, Russia',
ARRAY['Mikhail Gorbachev', 'Boris Yeltsin'],
ARRAY['ussr', 'dissolution', 'cold-war'],
'https://en.wikipedia.org/wiki/Dissolution_of_the_Soviet_Union',
'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/RIAN_archive_848095_Gorbachev_signing_law_on_ending_the_USSR.jpg/1024px-RIAN_archive_848095_Gorbachev_signing_law_on_ending_the_USSR.jpg');
